### ISSUE TITLE
Clicking on derivation history does nothing

### ISSUE THREAD

**Issue by rossduncan** [zxcalc/quantomatic#174]
I can't reproduce this consistently, but sometimes clicking on the derivation history causes the panel to become unresponsive, dropping the following exceptions in the console:
```
[error] Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException
```

**Comment by hmillerbakewell** [comment]
Do you have an example derivation where this occurs? The latest build (aimed at #178) may have fixed this for you, but I haven't been able to reproduce it.

**Comment by rossduncan** [comment]
Hi Hector,

I haven’t been able to reproduce it myself.  Seems that the GUI is really flakey at the moment.  I spent yesterday afternoon working on some simple derivations and on average I had to restart every 15 mins.  Fortunately when it falls over it doesn’t take everything with so you can save your work, but still very annoying.

-r

**Comment by hmillerbakewell** [comment]
Are you running from source or from .jar? And could we possibly have the memory capacity and speed of your computer?

**Comment by rossduncan** [comment]
Hi Hector,

I built from source yesterday.

My CPU is a 1.3GHz Intel Core i5 and it has 8GB of main memory.

-r

**Comment by hmillerbakewell** [comment]
Well that rules out those problems, as that's more powerful than the machine I'm developing on. Your java version is up to date, as is the code. I can't think why you're getting so many more errors than we are. Please keep us up to date if these things keep happening or you get an idea as to what's causing it.

Do your GUI problems only occur when you've been working on a file / derivation for a long time? It's possible it's due to the history storage.

**Comment by rossduncan** [comment]
HI Hector — only a couple of the derivations I had been working on were longer than a few rules.
-r

**Comment by hmillerbakewell** [comment]
The UI has been reworked since this bug was reported and this bug cannot be reproduced. Please re-open or create new a new issue if this persists after the next major update (expected before 2018-05-07)
