### ISSUE TITLE
Empty !-boxes not displayed

### ISSUE THREAD

**Issue by randomguy3** [zxcalc/quantomatic#27]
It is possible to have a graph with an empty !-box [not sure how you create one with the GUI, but...]

These should be displayed somewhere, so they can be manipulated or deleted.

**Comment by benjaminfrot** [comment]
I chose not to draw empty !-Boxes since the only thing we could do was to drop/kill them....
Instead, I think it's ok to add another button which allows a(n) (almost) full implementation of the core commands.
Two drawbacks though: 
- Empty !-Boxes are not displayed so one needs to click on the button to see that they are here.
- !-Boxes can be merged only two at a time. Core supports more than that.
