### ISSUE TITLE
Renaming bug when angle variables in pattern and target are the same

### ISSUE THREAD

**Issue by akissinger** [zxcalc/quantomatic#32]
Applying the spider rule (with angles alpha and beta) to connected vertices labelled alpha and 0 results in a merged vertex labelled 0. Oops.

Will post examples if I get a chance.

**Comment by randomguy3** [comment]
The issue here is that having the same names in the pattern and target of matchings for LinratExpr will lead to odd behaviour in LinratExpr.subst.  Possibly solutions: fix up LinratExpr.subst to deal with this, or have some sort of "rename_apart" type thing for data on vertices in rules.

LinratExpr also has other issues: firstly, it should more properly be LinratAngleExpr, since it assumes 2\pi == 0, and that any constant is a coeff of \pi.  Secondly, it does not deal well with patterns other than constants and single variables (with coefficients).

**Comment by benjaminfrot** [comment]
github.com/Quantomatic/quantomatic/commit/d6724dbf6f2952407bad6e70e2e9587449c0e88d
