### ISSUE TITLE
Choose a default theory and ruleset for first-time use

### ISSUE THREAD

**Issue by randomguy3** [zxcalc/quantomatic#55]
I dropped a copy of the red-green theory into a java resource folder, so it will always be available when running Quanto, and that is loaded when there is no saved theory (or the saved theory couldn't be loaded for some reason).

Would the substring theory be better?

What ruleset do we want to load by default?  Note that our example default.rules ruleset is actually broken.

**Comment by rossduncan** [comment]
Default ruleset = last used ruleset;  if undefined load the (fixed) red-green theory.

**Comment by randomguy3** [comment]
It will now load the last-used ruleset, but this was about the very first time it's started.

Currently, it loads the red-green theory, but no ruleset.  Long-term, do we want R-G?  If so, do we want it with or without hadamards?  What precise set of rules should be loaded?  Do we maybe want to load an example graph on first run?

**Comment by rossduncan** [comment]
Sorry - I should have written "ruleset" rather than "theory" above.  I had the (perhaps wrong) impression that the biggest fraction of the users was using some version of red-green.  Until that changes R-G (with hadamard) should be the default theory.  The default ruleset should be some well-behaved version of what is in the IQO paper - basically the ruleset we started with, but without the various weirdness to hack around old bugs in the bang box implementation.

**Comment by randomguy3** [comment]
That seems sensible.  It's easy enough to change it at a later date if other theories end up being more used.

**Comment by hmillerbakewell** [comment]
On creating a new project there's now a drop-down list of provided theories, as well as the option of inheriting the theory from an existing project. Rulesets are provided via the separate sample-projects repository (along with the relevant theory files.)

Theory editing is now available directly inside a project.
