### ISSUE TITLE
100% CPU usage when quanto is open

### ISSUE THREAD

**Issue by iislucas** [zxcalc/quantomatic#58]
When I open the GUI, I get 100% CPU usage. This is on MacOS 10.6; nothing special has to be done, just open it and hear the computer scream. :)

Guess: we had an issue like this a while ago do with making animation of moving vertices stop when vertices were close enough to their final position. Maybe this got lost?

**Comment by randomguy3** [comment]
The same issue doesn't seem to appear on Unix, but there doesn't seem to be any OS-specific code in Quanto that could be causing this.

Any chance you can do some profiling?  In NetBeans, just hit the profile button, and tell it to use the profile-nb target.  Otherwise, the jvisualvm tool (comes with the JDK) should work.

**Comment by zamdzhiev** [comment]
The old GUI is no longer in development, check out the new one.
